version: '2'
services:
  db:
    image: nouchka/sqlite3:latest
    volumes:
      - var/lib/sqlite3
    stdin_open: true
    tty: true

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/EmployeeDemo
    ports:
      - "3000:3000"
    depends_on:
      - db
