version: '2'
services:
  db:
    image: nouchka/sqlite3:latest
    volumes:
      - var/lib/sqlite3
    stdin_open: true
    tty: true

  redis:
    image: 'redis:6.2.11-alpine'
    command: redis-server
    volumes:
      - 'redis:/data'

  sidekiq:
    depends_on:
      - db
      - redis
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/EmployeeDemo
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/EmployeeDemo
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1
volumes:
  redis:
  postgres:
